### ISSUE TITLE
Where to get support?

### ISSUE THREAD

**Issue by iahung2** [frang75/nappgui_src#71]
Is there an active community? The Discussions page of this repository is too quiet. You sometimes popped up and then just off into nowhere. Btw, I will not go to StackOverflow. I don't want my questions to be closed for no reasons. I'm not a professional developers. I don't want to join that community. As you said on your website, just go to StackOverflow to ask questions. I browsed the [[nappgui]](https://stackoverflow.com/questions/tagged/nappgui) tag. Do you know what I found? I found that exactly no questions are posted under this tag!

**Comment by frang75** [comment]
Dear @iahung2!

More than 10 years ago I started developing NAppGUI. I made the OpenSource project two years ago, so that anyone can use it freely. I continue to maintain the project in my free time, also for free. Therefore, you can do three things:
* Find another project that lives up to your expectations.
* Sponsor the project, as some companies do, hiring my services to urgently implement any feature you need.
* Download the NAppGUI book (also free), start programming and follow its numerous examples and detailed documentation. https://nappgui.com/ebook/ndoc_en.pdf

But:
If what you're looking for is to play Project Manager, or just get my attention for free, you're wrong. I advise you to look for a girlfriend, or boyfriend, or pet, or hobby. From now on you are banned from the project.

Thank you very much for your cooperation.
Sincerely.
