### ISSUE TITLE
Products demo report an error in the mac m1

### ISSUE THREAD

**Issue by millken** [frang75/nappgui_src#96]
<img width="569" alt="image" src="https://github.com/frang75/nappgui_src/assets/176581/f3f9f567-0974-4ea7-b1c2-e1e316202269">

**Comment by frang75** [comment]
Hi @millken!
Apple has changed the NSMenu implementation in macOS Sonoma. 
https://developer.apple.com/documentation/macos-release-notes/appkit-release-notes-for-macos-14

This NAppGUI check became obsolete. Fixed in this commit: https://github.com/frang75/nappgui_src/commit/197c7db6c41b8bde7e01532d4943ee95d4e8ca7e

Thanks for report!

**Comment by millken** [comment]
Thanks, It works as expected.
